#slicing indexing 
s =  "chaKri67"
print(s[::-1])
print(s[1:4])
print(s[0:4])
print(s[:4])
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.find("chakri"))
print(s.count("a"))
print(s.replace("chakri","salaar"))
print(s.endswith(".com"))
print(s.isalpha())
print(s.isdigit())
print(s.swapcase())
print(s.title())
print(s.strip())
print(s.split())
print(".".join("chakri"))